config/routes.rb
Rails.application.routes.draw do
  root to: 'static#landing'

  get :home, controller: :static
  get :vokalna_glasba, controller: :static
  get :instrumentalna_glasba, controller: :static
  get :kompozicije, controller: :static
  get :seminarji, controller: :static
  get :izobrazevanja, controller: :static
  get :galerija, controller: :static

  get :cv, controller: :static
  get :sporocilo, controller: :static
  post :sporocilo, controller: :static, action: :handle_message

  get :narocilo, controller: :static
  post :narocilo, controller: :static, action: :handle_message_narocilo

  get :nakup, controller: :static
  post :nakup, controller: :static, action: :handle_message_nakup

  resources :posts, only: [:show]
  resources :albums, only: [:show]

  get :cookies, controller: :static, action: :cookies_info

  namespace :admin do
    root to: 'pages#index'

    resources :pages
    resources :posts do
      get :move_up
      get :move_down
    end
    resources :albums do
      get :move_up
      get :move_down
      resources :pictures, only: [:destroy]
    end
  end

  # Tinymce uploads
  post '/tinymce_assets' => 'tinymce_assets#create'
end

app/models/album.rb
class Album < ActiveRecord::Base

  ### Attributes
  #
  # name
  # position
  # content : text
  #

  acts_as_list

  attr_accessor :image_urls

  has_many :pictures, dependent: :destroy

  # serialize :image_urls, Array
  serialize :name, Hash
  serialize :content, Hash

  after_save :create_pictures, if: :image_urls

  def create_pictures
    image_urls.each do |url|
      Picture.create({
        album: self,
        image_url: url
      })
    end
  end

  def localized_name locale=I18n.locale
    name[locale] || ""
  end

  def localized_content locale=I18n.locale
    content[locale] || ""
  end

  I18n.available_locales.each do |locale|
    define_method "#{locale}_name" do
      name[locale]
    end

    define_method "#{locale}_name=" do |val|
      name[locale] = val
    end

    define_method "#{locale}_content" do
      content[locale]
    end

    define_method "#{locale}_content=" do |val|
      content[locale] = val
    end
  end

  def image_presigned_post
    @image_presigned_post ||= S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
  end
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController

  expose(:albums) { Album.all }
  expose(:album, attributes: :album_attributes)

  def create
    if album.save
      redirect_to admin_albums_path
    else
      render :new
    end
  end

  def update
    if album.save
      redirect_to admin_albums_path
    else
      render :edit
    end
  end

  def destroy
    album.destroy
    redirect_to admin_albums_path
  end

  def move_up
    album.move_higher
    redirect_to admin_albums_path
  end

  def move_down
    album.move_lower
    redirect_to admin_albums_path
  end


  private
  def locale_names
    I18n.available_locales.map do |locale|
      [locale, :name].join('_').to_sym
    end
  end

  def locale_content
    I18n.available_locales.map do |locale|
      [locale, :content].join('_').to_sym
    end
  end

  def album_attributes
    permitted_params = [:position, image_urls: []] + locale_names + locale_content
    params.require(:album).permit(permitted_params)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  layout 'application'

  expose(:album)

  def show
  end
end

app/views/admin/albums/_form.html.haml
= form_for album, url: (album.new_record? ? admin_albums_path : admin_album_path(album)), html: { class: 'form-horizontal' } do |f|
  - if album.errors.any?
    #error_explanation
      %h2= "#{pluralize(album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - album.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    .col-sm-offset-2.col-sm-5.text-center
      %h4 Slovenščina
    .col-sm-5.text-center
      %h4 Angleščina

  .form-group
    = f.label :sl_name, "Naziv", class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :sl_name, class: 'form-control'
    .col-sm-5
      = f.text_field :en_name, class: 'form-control'

  .form-group
    = f.label :sl_content, "Opis", class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_area :sl_content, class: 'form-control'
    .col-sm-5
      = f.text_area :en_content, class: 'form-control'


  %hr
  .form-group
    .col-sm-offset-2.col-sm-10
      %h4 Slike

  .form-group
    .col-sm-offset-2.col-sm-5
      %table.table
        - album.pictures.each do |p|
          %tr{ id: "picture_#{p.id}_row"}
            %td= image_tag p.image.url(:thumb), width: 50
            %td.text-right= link_to 'Delete image', admin_album_picture_path(album, p), method: :delete, class: 'btn btn-danger btn-sm', :'data-confirm' => "Ali ste prepričani?", :'data-remote' => true

  .form-group
    = f.label :image_urls, "Naloži več", class: 'col-sm-2 control-label'
    .col-sm-3
      = f.file_field :image_urls, multiple: true, class: 'direct-upload form-control'
    #uploaded-images.col-sm-7

  %hr
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Posodobi', class: 'btn btn-primary'
      = link_to 'Nazaj', admin_albums_path, class: 'btn btn-default'

= render 'shared/upload_script', format: :js, album: album

app/views/admin/albums/edit.html.haml
%h1 Urejanje albuma #{album.localized_name}

= render 'form', album: album

app/views/admin/albums/index.html.haml
%h1 Pregled albumov

%table.table
  %tr
    %th
    %th Prva slika
    %th Ime
    %th Slike
    %th Ustvarjen
    %th

  - albums.order(:position).each do |album|
    %tr
      %td
        .link
          = link_to admin_album_move_up_path(album) do
            %span.glyphicon.glyphicon-chevron-up
        .link
          = link_to admin_album_move_down_path(album) do
            %span.glyphicon.glyphicon-chevron-down
      %td= image_tag(album.pictures.first.image.url(:thumb), width: 100) rescue nil
      %td
        = album.localized_name(:sl)
        %br
        = album.localized_name(:en)
      %td
        - album.pictures.last(5).each do |i|
          = image_tag(i.image.url(:thumb), width: 50)

      %td= time_ago_in_words(album.created_at)+' nazaj'
      %td
        = link_to 'Uredi', edit_admin_album_path(album), class: 'btn btn-primary'
        = link_to 'Izbriši', admin_album_path(album), method: :delete, :'data-confirm' => 'Ste prepričani da želite izbrisati album?', class: 'btn btn-danger'

%p
  = link_to '+ Dodaj album', new_admin_album_path, class: 'btn btn-success'

app/views/admin/albums/new.html.haml
%h1 Ustvarjanje novega albuma

= render 'form', album: album