config/routes.rb
Rails.application.routes.draw do
  root to: 'static#landing'

  get :home, controller: :static
  get :vokalna_glasba, controller: :static
  get :instrumentalna_glasba, controller: :static
  get :kompozicije, controller: :static
  get :seminarji, controller: :static
  get :izobrazevanja, controller: :static
  get :galerija, controller: :static

  get :cv, controller: :static
  get :sporocilo, controller: :static
  post :sporocilo, controller: :static, action: :handle_message

  get :narocilo, controller: :static
  post :narocilo, controller: :static, action: :handle_message_narocilo

  get :nakup, controller: :static
  post :nakup, controller: :static, action: :handle_message_nakup

  resources :posts, only: [:show]
  resources :albums, only: [:show]

  get :cookies, controller: :static, action: :cookies_info

  namespace :admin do
    root to: 'pages#index'

    resources :pages
    resources :posts do
      get :move_up
      get :move_down
    end
    resources :albums do
      get :move_up
      get :move_down
      resources :pictures, only: [:destroy]
    end
  end

  # Tinymce uploads
  post '/tinymce_assets' => 'tinymce_assets#create'
end

app/views/shared/_ga_script.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GA_CODE'] %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_menu.html.haml
%ul
  %li
    = link_to Page.by_shortcode(:index).title, home_path

  %li
    = link_to '#' do
      %i.arrow
      = t('glasbene_tiskovine')
    %ul.dropdown
      %li
        = link_to Page.by_shortcode(:vokal).title, vokalna_glasba_path
      %li
        = link_to Page.by_shortcode(:instrumental).title, instrumentalna_glasba_path

  %li
    = link_to Page.by_shortcode(:kompozicije).title, kompozicije_path

  %li
    = link_to '#' do
      %i.arrow
      = t('izobrazevanje')
    %ul.dropdown
      %li
        = link_to Page.by_shortcode(:seminarji).title, seminarji_path
      %li
        = link_to Page.by_shortcode(:izobrazevanja).title, izobrazevanja_path

  %li
    = link_to t('galerija'), galerija_path

app/views/shared/_opusi.html.haml
.opusi
  - opusi.order(:position).each do |opus|
    .opus
      .image
        = link_to post_path(opus) do
          .overlay
          = image_tag opus.images.first.thumb.url, width: 50, style: 'border: 1px solid #dedede'
      .details
        .title
          = link_to post_path(opus) do
            = opus.orginal_naslov

          - if opus.localized_naslov.present?
            %small
              %i= opus.localized_naslov

        - if opus.localized_avtor.present?
          .avtor= opus.localized_avtor

        - if opus.localized_zasedba.present?
          .zasedba=opus.localized_zasedba

      .clearer

  .apple_pagination
    = will_paginate opusi

app/views/shared/_upload_script.html.haml
:coffeescript
  $ ->
    $(".direct-upload").each (i, elem) ->
      fileInput = $(elem)
      form = $(fileInput.parents("form:first"))
      submitButton = form.find("input[type=\"submit\"]")
      progressBar = $("<div class='progress-bar progress-bar-success progress-bar-striped'></div>")
      barContainer = $("<div class='progress'></div>").append(progressBar)
      fileInput.after barContainer

      fileInput.attr("orig_name", fileInput.attr("name"))
      fileInput.attr("name", "file_upload")

      fileInput.fileupload
        fileInput: fileInput
        url: "#{album.image_presigned_post.url}"
        type: "POST"
        autoUpload: true
        formData: #{album.image_presigned_post.fields.to_json.html_safe}
        paramName: "file" # S3 does not like nested name fields i.e. name="user[avatar_url]"
        dataType: "XML" # S3 returns XML if success_action_status is set to 201
        replaceFileInput: false

        progressall: (e, data) ->
          filesCount = parseInt(fileInput.attr('files_count'))
          filesLoaded = (parseInt(fileInput.attr('files_loaded')) || 0)

          progress = parseInt((data.loaded + filesLoaded*(data.total*0.2 / filesCount)) / (data.total*1.2) * 100, 10)
          progressBar.css "width", progress + "%"

        start: (e) ->
          submitButton.prop "disabled", true
          progressBar.css("width", "0%").text "Loading..."

          fileInput.attr('files_count', e.target.files.length)

        done: (e, data) ->
          # extract key and generate URL from response
          key = $(data.jqXHR.responseXML).find("Key").text()
          url = "//#{album.image_presigned_post.url.host}/" + key

          # create hidden field
          input = $("<input />",
            type: "hidden"
            name: fileInput.attr("orig_name")
            value: url
          )
          form.append input

          # create img filed
          image = $("<img src="+url+" width=100 />")
          $("#uploaded-images").append image

          filesCount = parseInt(fileInput.attr('files_count'))
          filesLoaded = (parseInt(fileInput.attr('files_loaded')) || 0) + 1
          fileInput.attr('files_loaded', filesLoaded)

          if filesLoaded == filesCount
            submitButton.prop "disabled", false
            progressBar.text "Uploading done"
            progressBar.css "width", "100%"

        fail: (e, data) ->
          submitButton.prop "disabled", false
          progressBar.css("background", "red").text "Failed"