config/routes.rb
Rails.application.routes.draw do
  root to: 'static#landing'

  get :home, controller: :static
  get :vokalna_glasba, controller: :static
  get :instrumentalna_glasba, controller: :static
  get :kompozicije, controller: :static
  get :seminarji, controller: :static
  get :izobrazevanja, controller: :static
  get :galerija, controller: :static

  get :cv, controller: :static
  get :sporocilo, controller: :static
  post :sporocilo, controller: :static, action: :handle_message

  get :narocilo, controller: :static
  post :narocilo, controller: :static, action: :handle_message_narocilo

  get :nakup, controller: :static
  post :nakup, controller: :static, action: :handle_message_nakup

  resources :posts, only: [:show]
  resources :albums, only: [:show]

  get :cookies, controller: :static, action: :cookies_info

  namespace :admin do
    root to: 'pages#index'

    resources :pages
    resources :posts do
      get :move_up
      get :move_down
    end
    resources :albums do
      get :move_up
      get :move_down
      resources :pictures, only: [:destroy]
    end
  end

  # Tinymce uploads
  post '/tinymce_assets' => 'tinymce_assets#create'
end

app/models/post.rb
class Post < ActiveRecord::Base

  ### Attributes
  #
  # orginal_naslov
  # naslov
  # avtor
  # zasedba
  # leto_nastanka : integer
  # lang
  # vrsta_izdaje
  # kataloska_st
  # ismn
  # opis : text
  # vokalna : boolean
  # instrumentalna : boolean
  # novo : boolean

  # besedilo
  # cena : text
  # file : string
  # file_avatar : string
  # images : text

  # youtube
  # mp3
  # free : boolean

  # position

  acts_as_list

  scope :vokalna, ->{ where vokalna: true }
  scope :instrumentalna, ->{ where instrumentalna: true }

  scope :newest, ->{ where(novo: true).order(created_at: :desc).first(2) }

  serialize :images, Array

  Post::MultilangAttrs = [ :naslov, :avtor, :besedilo, :zasedba,
    :lang, :vrsta_izdaje, :opis, :cena ]

  Post::MultilangAttrs.each do |attr_name|
    serialize attr_name, Hash

    define_method "localized_#{attr_name}" do |locale = I18n.locale|
      self.try(attr_name)[locale] || ""
    end

    I18n.available_locales.each do |locale|
      define_method "#{locale}_#{attr_name}" do
        self.try(attr_name)[locale]
      end

      define_method "#{locale}_#{attr_name}=" do |val|
        self.try(attr_name)[locale] = val
      end
    end
  end

  mount_uploader :file, PdfUploader
  mount_uploaders :images, PdfImageUploader
  mount_uploader :mp3, Mp3Uploader

  has_many :relatives
  has_many :related_posts, through: :relatives, source: :relative

  attr_accessor :related_post_ids

  validates_presence_of :orginal_naslov
  validates_presence_of :file

  before_validation :pdf_to_images, if: :file_changed?
  after_save :set_related_posts, unless: ->{ related_post_ids.nil? }

  def set_related_posts
    relatives.destroy_all

    related_post_ids.select(&:present?).each do |post_id|
      Relative.create({
        post: self,
        relative: Post.find(post_id)
      })
    end
  end

  def pdf_to_images
    puts "Starting"
    @pdf_file = MiniMagick::Image.open(self.file.path)
    self.images = @pdf_file.pages.each_with_index.map do |page, i|
      puts "Processing page #{i+1} ..."
      page.combine_options do |p|
        p.density(200)
        p.write(page.path+"#{i}.jpg")
      end

      puts "Uploading with carrierwave"
      File.open(page.path+"#{i}.jpg")
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  expose(:post, attributes: :post_attributes)

  def index
  end

  def edit
  end

  def update
    if post.save
      redirect_to admin_posts_path
    else
      render :edit
    end
  end

  def create
    if post.save
      redirect_to admin_posts_path
    else
      render :edit
    end
  end

  def destroy
    post.destroy!
    redirect_to admin_posts_path
  end

  def move_up
    post.move_higher
    redirect_to admin_posts_path
  end

  def move_down
    post.move_lower
    redirect_to admin_posts_path
  end

  private
  def post_attributes
    params.require(:post).permit!
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'application'

  expose(:post)

  def show
  end
end

app/views/admin/posts/_form.html.haml
= form_for post, url: (post.new_record? ? admin_posts_path : admin_post_path(post)), html: { class: 'form-horizontal' } do |f|


  .form-group
    = f.label :file, 'PDF', class: 'col-sm-2 control-label'
    .col-sm-5
      = f.file_field :file, class: 'form-control'

      - if post.errors.include? :file
        %snap.label.label-danger Napaka PDF je obvezen

    .col-sm-5
      .checkbox
        = f.label :free do
          = f.check_box :free
          PDF na voljo za prenos

  - unless post.images.empty?
    .form-group
      .col-sm-10.col-sm-offset-2
        - post.images.each do |img|
          = link_to img.url, class: 'touch' do
            = image_tag img.thumb.url, width: 50


  .form-group
    = f.label :leto_nastanka, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :leto_nastanka, class: 'form-control'

  .form-group
    = f.label :kataloska_st, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :kataloska_st, class: 'form-control'

  .form-group
    = f.label :ismn, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :ismn, class: 'form-control'

  .form-group
    = f.label :youtube, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :youtube, class: 'form-control', placeholder: "Naprimer: https://www.youtube.com/watch?v=IOYyCHGWJq4"
    - if post.youtube?
      %label.control-label= link_to "#{post.youtube}", post.youtube

  .form-group
    = f.label :mp3, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.file_field :mp3, class: 'form-control'
    - if post.mp3?
      .col-sm-5
        %label.control-label= link_to "*** MP3 je naložen", post.mp3.url

  .form-group
    .col-sm-5.col-sm-offset-2.text-center
      %h3 Slovenski jezik
    .col-sm-5.text-center
      %h3 Angleški jezik

  .form-group
    = f.label :orginal_naslov, 'Orginalen naslov:', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :orginal_naslov, class: 'form-control'

      - if post.errors.include? :orginal_naslov
        %snap.label.label-danger Napaka, naslov je obvezen

  .form-group
    = f.label :naslov, 'Prevod', class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :sl_naslov, class: 'form-control'

    .col-sm-5
      = f.text_field :en_naslov, class: 'form-control'


  .form-group
    = f.label :avtor, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :sl_avtor, class: 'form-control'
    .col-sm-5
      = f.text_field :en_avtor, class: 'form-control'

  .form-group
    = f.label :besedilo, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :sl_besedilo, class: 'form-control'
    .col-sm-5
      = f.text_field :en_besedilo, class: 'form-control'

  .form-group
    = f.label :zasedba, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :sl_zasedba, class: 'form-control'
    .col-sm-5
      = f.text_field :en_zasedba, class: 'form-control'

  .form-group
    = f.label :lang, 'Jezik', class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :sl_lang, class: 'form-control'
    .col-sm-5
      = f.text_field :en_lang, class: 'form-control'

  .form-group
    = f.label :vrsta_izdaje, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_field :sl_vrsta_izdaje, class: 'form-control'
    .col-sm-5
      = f.text_field :en_vrsta_izdaje, class: 'form-control'

  .form-group
    = f.label :opis, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_area :sl_opis, :class => "tinymce", :rows => 10, :cols => 120, class: 'tinymce form-control'
    .col-sm-5
      = f.text_area :en_opis, :class => "tinymce", :rows => 10, :cols => 120, class: 'tinymce form-control'

  .form-group
    = f.label :cena, class: 'col-sm-2 control-label'
    .col-sm-5
      = f.text_area :sl_cena, :class => "tinymce", :rows => 10, :cols => 120, class: 'tinymce form-control'
    .col-sm-5
      = f.text_area :en_cena, :class => "tinymce", :rows => 10, :cols => 120, class: 'tinymce form-control'


  .form-group
    .col-sm-10.col-sm-offset-2
      .checkbox
        %label
          = f.check_box :vokalna
          Vokalna glasba
      .checkbox
        %label
          = f.check_box :instrumentalna
          Instrumentalna glasba

      .checkbox
        %label
          = f.check_box :novo
          Novo!


  .form-group
    = f.label :related_post_ids, 'Sorodni produkti', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.select :related_post_ids, Post.where.not(id: post.id).map{|p| [p.orginal_naslov, p.id, selected: (post.related_posts.include?(p))] }, {}, { :multiple => true, :size => Post.count, class: 'form-control' }

  .form-group
    .col-sm-10.col-sm-offset-2
      = link_to 'Prekliči', admin_posts_path, class: 'btn btn-danger'
      = f.submit 'Shrani', class: 'btn btn-primary'

app/views/admin/posts/edit.html.haml
.row
  .col-sm-10.col-sm-offset-2
    %h1 Urejanje produkta

= render 'form', post: post

app/views/admin/posts/index.html.haml
%h1 Tiskovine
%small Število vseh tiskovin v bazi: #{Post.count}

%table.table
  %tr
    %th
    %th Naslov
    %th Avtor
    %th Besedilo
    %th Zasedba
    %th Leto nastanka
    %th Jezik
    %th Vrsta izdaje
    %th Kataloska Št.
    %th ISMN
    %th Kategorije
    %th

  - Post.all.order(:position).each do |opus|
    %tr
      %td
        .link
          = link_to admin_post_move_up_path(opus) do
            %span.glyphicon.glyphicon-chevron-up
        .link
          = link_to admin_post_move_down_path(opus) do
            %span.glyphicon.glyphicon-chevron-down
      %td= opus.orginal_naslov
      %td= opus.localized_avtor
      %td= opus.localized_besedilo
      %td= opus.localized_zasedba
      %td= opus.leto_nastanka
      %td= opus.localized_lang
      %td= opus.localized_vrsta_izdaje
      %td= opus.kataloska_st
      %td= opus.ismn
      %td
        - if opus.vokalna?
          .label.label-primary Vokalna
        - if opus.instrumentalna?
          .label.label-primary Instrumentalna
        - if opus.novo?
          .div
            %span.label.label-primary Novo
      %td
        = link_to 'Uredi', edit_admin_post_path(opus), class: 'btn btn-primary'
        = link_to 'Izbriši', admin_post_path(opus), :method => :delete, :data => { :confirm => 'Ste prepričani?' }, class: 'btn btn-danger'

%br
%br
%p
  = link_to '+ Dodaj tiskovino', new_admin_post_path, class: 'btn btn-primary pull-right'

app/views/admin/posts/new.html.haml
.row
  .col-sm-10.col-sm-offset-2
    %h1 Dodajanje produkta

= render 'form', post: post