config/routes.rb
Rails.application.routes.draw do
  root to: 'static#landing'

  get :home, controller: :static
  get :vokalna_glasba, controller: :static
  get :instrumentalna_glasba, controller: :static
  get :kompozicije, controller: :static
  get :seminarji, controller: :static
  get :izobrazevanja, controller: :static
  get :galerija, controller: :static

  get :cv, controller: :static
  get :sporocilo, controller: :static
  post :sporocilo, controller: :static, action: :handle_message

  get :narocilo, controller: :static
  post :narocilo, controller: :static, action: :handle_message_narocilo

  get :nakup, controller: :static
  post :nakup, controller: :static, action: :handle_message_nakup

  resources :posts, only: [:show]
  resources :albums, only: [:show]

  get :cookies, controller: :static, action: :cookies_info

  namespace :admin do
    root to: 'pages#index'

    resources :pages
    resources :posts do
      get :move_up
      get :move_down
    end
    resources :albums do
      get :move_up
      get :move_down
      resources :pictures, only: [:destroy]
    end
  end

  # Tinymce uploads
  post '/tinymce_assets' => 'tinymce_assets#create'
end

app/views/layouts/admin.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/

    %title Musicales.si | Admin
    = stylesheet_link_tag    'admin', media: 'all'
    = javascript_include_tag 'admin'
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => root_path} musicales.si
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Vsebina', admin_root_path
            %li
              = link_to 'Tiskovine', admin_posts_path
            %li
              = link_to 'Galerija', admin_albums_path

    .container
      = yield
      .clearfix

      %hr
      %footer
        %p © Company 2014

    = tinymce

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ARTES MUSICALES, Aleš Makovac s.p.
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'shared/ga_script'

  %body
    .page-container
      .lang
        .lang-menu
          = link_to url_for(locale: :sl) do
            = image_tag 'main/slo.png', style: 'vertical-align:top'
          = link_to url_for(locale: :en) do
            = image_tag 'main/uk.png', style: 'vertical-align:top'
      .header
        = link_to root_path do
          = image_tag 'main/logo_top_png.png', style: 'vertical-align:top'
        %h2
          Aleš Makovac
          %br
          = t('slogan')
      .navigation
        = render 'shared/menu'
        .clearer  
      .content
        .mainbar
          .contentdiv
            = yield
            .clearer
          .news
            - unless Post.newest.empty?
              %h2 #{t 'new'}!

            - Post.newest.each do |p|
              .aktual
                = link_to post_path(p) do
                  / .line
                  /   %label.novo novo!
                  - unless p.images.empty?
                    = image_tag p.images.first.url, width: 100, style: 'border: 1px solid #dedede'
                  .line.color-blink
                    %strong= p.orginal_naslov
                  .line.color-blink
                    %small
                      %i= p.localized_naslov
                  .line= p.localized_avtor
                  .line= p.localized_zasedba

          .clearer
        .footer
          .fcontainerimg
            = image_tag 'main/logo_footer.jpg', height: 100, width: 100
          .fcontainer
            %strong ARTES MUSICALES
            %br/
            %strong Aleš Makovac s.p.
            %br/
            Na žago 17
            %br/
            8351 Straža
          .fcontainer
            %strong Tel:
            +386 (0)51 384 989
          .fcontainer
            %strong E-mail:
            %a{:href => "mailto:ales.makovac@gmail.com"} ales.makovac@gmail.com
            %br/
            / %strong E-mail:
            / info@musicales.si
            / %br/
          .fcontainer
            %ul{:style => "margin:0 0 0 50px; padding: 0;"}
              %li
                = link_to t('prva_stran'), root_path
              %li
                = link_to t('pustite_sporocilo'), sporocilo_path
              %li
                = link_to t('oddajte_narocilo'), narocilo_path
              %li
                = link_to t('piskotki'), cookies_path
          .clearer
    = render 'cookies_eu/cookies_eu'